### ISSUE TITLE
关于书籍结构和脚本结构

### ISSUE THREAD

**Issue by arlenesu** [less-crowds/gentoo-beginner-to-advanced#1]
书籍结构应该和脚本结构不一样
书籍应该更加详细
脚本可以略微缩减

**Comment by Ivy-zoe** [comment]
书籍的部分我也在考虑加入一下 组成原理的内容。
脚本部分目前还没有开始写的计划，可能需要你来写了。
有个可以共同编辑的roadmap会好点
